collision_detector:
  outside_polygon:
    - [ -5, -5 ]
    - [ -5, 5 ]
    - [ 5, 5 ]
    - [ 5, -5 ]

  inside_polygon:
    - [ [ -5, 1 ], [ -5, 5 ], [ 5, 5 ], [ 5, 1 ] ]
    - [ [ -5, -1 ], [ -1, -1 ], [ -1, -5 ], [ -5, -5 ] ]
    - [ [ -1, -3 ], [ 2, -3 ], [ 2, -5 ], [ -1, -5 ] ]
    - [ [ 2, -1 ], [ 5, -1 ], [ 5, -5 ], [ 2, -5 ] ]

  robot_shapes:
    - [ [ -0.5, -0.25 ], [ -0.5, 0.25 ], [ 0.5, 0.25 ], [ 0.5, -0.25 ] ]
    - [ [ -0.5, -0.25 ], [ -0.5, 0.25 ], [ 0.5, 0.25 ], [ 0.5, -0.25 ] ]

start: [ [ -4, 0, 0 ], [ 4, 0, 3.1415 ] ]

goal: [ [ 4, 0, 0 ], [ -4, 0, 3.1415 ] ]

bounds:
  min_x: -5
  max_x: 5
  min_y: -5
  max_y: 5
type_: MultiRobotPathPlannerTask