collision_model_point_sampler:
  course_random_offset: 1.0
  fine_random_offset: 0.2
  angle_random_offset: 1
  point_count: 1000
collision_neural_field_model_trainer:
  optimizer:
    lr: 0.01
    beta1: 0.9
    beta2: 0.9
  collision_model_factory:
    mean: 0
    sigma: 1.0
    encoding_dimension: 128
    hidden_dimensions: [128, 128, 128]
path_optimizer:
  optimizer:
    lr: 0.1
    beta1: 0.9
    beta2: 0.9
    lagrange_multiplier_lr: 100
    base_lr: 0.005
    max_lr: 0.005
    step_size_up: 100
    step_size_down: 100
  loss_builder:
    regularization_weight: 0.5
    collision_weight: 0.06
    direction_constraint_weight: 30
    second_differences_weight: 30
  state_initializer:
    path_state_count: 100
  grad_preconditioner:
    velocity_hessian_weight: 300

reparametrize_rate: 10
type_: MultiProcessWarehouseNFOMP
