collision_neural_field_model_trainer:
  collision_model_point_sampler:
    course_random_offset: 5.0
    fine_random_offset: 1.0
    angle_random_offset: 1
  optimizer:
    lr: 0.05
    beta1: 0.9
    beta2: 0.9
  collision_model_factory:
    mean: 0
    sigma: 3.0
    encoding_dimension: 128
    hidden_dimensions: [128, 128, 128]
path_optimizer:
  optimizer:
    lr: 0.1
    beta1: 0.9
    beta2: 0.9
    lagrange_multiplier_lr: 100
    base_lr: 0.002
    max_lr: 0.02
    step_size_up: 50
    step_size_down: 50
  loss_builder:
    regularization_weight: 0.5
    collision_weight: 0.06
    direction_constraint_weight: 10
    second_differences_weight: 1
  state_initializer:
    path_state_count: 100
  grad_preconditioner:
    velocity_hessian_weight: 0.5

reparametrize_rate: 10
type_: WarehouseNFOMP
